'use strict';

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('authorNews', {
    id: { type: DataTypes.INTEGER(), allowNull: false , primaryKey: true},
    subject: { type: DataTypes.STRING(255), allowNull: false },
    summary: { type: DataTypes.STRING(1022), allowNull: true },
    content: { type: DataTypes.TEXT('medium'), allowNull: false},
    publish_time: { type: DataTypes.NOW(), allowNull: true },
    publish_author_id: { type: DataTypes.INTEGER(), allowNull: true },
    read_count: { type: DataTypes.INTEGER(), allowNull: true },
    category_id: { type: DataTypes.INTEGER(), allowNull: true },
    status: { type: DataTypes.INTEGER(), allowNull: false },
    content_template_id: { type: DataTypes.INTEGER(), allowNull: false },
    news_url: { type: DataTypes.STRING(255), allowNull: true },
    news_source: { type: DataTypes.STRING(31), allowNull: false },
    news_source_url: { type: DataTypes.STRING(255), allowNull: true },
    news_author: { type: DataTypes.STRING(63), allowNull: true },
    thumbnail_url: { type: DataTypes.STRING(255), allowNull: true },
    video_url: { type: DataTypes.STRING(255), allowNull: true },
    news_type: { type: DataTypes.INTEGER(), allowNull: false },
    news_keywords: { type: DataTypes.STRING(4902), allowNull: true },
    news_sensitive_words: { type: DataTypes.STRING(4092), allowNull: true },
    config_id: { type: DataTypes.INTEGER(), allowNull: true },
    user_name: { type: DataTypes.STRING(32), allowNull: false },
    name: { type: DataTypes.STRING(32), allowNull: true },
    password: { type: DataTypes.STRING(64), allowNull: false},
    enable: { type: DataTypes.INTEGER(1), allowNull: false },
    isAdmin: { type: DataTypes.INTEGER(1), allowNull: false },
    login_ip: { type: DataTypes.STRING(32), allowNull: true },
    login_fail_num: { type: DataTypes.INTEGER(3), allowNull: true },
    home_phone: { type: DataTypes.STRING(15), allowNull: true },
    mobile: { type: DataTypes.STRING(15), allowNull: true },
    create_date: { type: DataTypes.DATE(), allowNull: false },
    create_user: { type: DataTypes.STRING(40), allowNull: false },
    update_date: { type: DataTypes.DATE(), allowNull: true },
    update_user: { type: DataTypes.STRING(40), allowNull: true },
    sex: { type: DataTypes.INTEGER(1), allowNull: true },
    age: { type: DataTypes.INTEGER(3), allowNull: true },
    qq: { type: DataTypes.STRING(32), allowNull: true },
    email: { type: DataTypes.STRING(64), allowNull: true },
    head_img_url: { type: DataTypes.STRING(300), allowNull: true },
    description: { type: DataTypes.STRING(300), allowNull: true },
    nick_name: { type: DataTypes.STRING(30), allowNull: true },
    good_at_category: { type: DataTypes.STRING(32), allowNull: true }
  }, {});  
};